name: assign-from-label
run-name: "assign-from-label: '${{ github.event.label.name }}'"

on:
  issues:
    types:
      - labeled
  pull_request:
    types:
      - labeled

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  assign-from-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pietrobolcato/action-read-yaml@1.1.0
        id: metadata
        with:
          config: .github/assets/user-labels.yml

      - name: assign
        if: ${{ steps.metadata.outputs[github.event.label.name]  != '' }}
        run: |
          gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ steps.metadata.outputs[github.event.label.name] }}
